dist: bionic

language: cpp

os:
  - linux

compiler:
  - gcc
  - clang
  
env:
  - BUILD_CONFIGURATION=Debug
  - BUILD_CONFIGURATION=Release

addons:
  apt:
    update: true
    packages:
      - cmake-data
      - cmake

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get -y install libboost-filesystem-dev libboost-system-dev libgtest-dev build-essential
    - mkdir build-gtest
    - cd build-gtest
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release /usr/src/gtest/
    - sudo make install
    - cd ..

script:
  - eval "${MATRIX_EVAL}"
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION .. 
  - make
  - ctest --output-on-failure
