dist: bionic

language: cpp

os:
  - linux

compiler:
  - clang
  - gcc

env:
  - BUILD_CONFIGURATION=Debug
  - BUILD_CONFIGURATION=Release

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-bionic-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

addons:
  apt:
    update: true
    packages:
      - cmake-data
      - cmake

before_install:
    - eval "${MATRIX_EVAL}"
    - sudo apt-get -y install libboost-all-dev libgtest-dev build-essential
    - mkdir build-gtest
    - cd build-gtest
    - cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_BUILD_TYPE=Release /usr/src/gtest/
    - sudo make install
    - cd ..

script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION .. 
  - make
  - ctest --output-on-failure
