shallow_clone: true

image:
    - Visual Studio 2019
  
platform:
    - x86
    - x64
    
configuration:
    - Debug 
    - Release
    
branches:
    only:
        - master
        
build_script:
    - mkdir build
    - cd build
    - cmake -DBOOST_ROOT=C:\Libraries\boost_1_71_0 -DBoost_USE_STATIC_LIBS=ON -DCMAKE_BUILD_TYPE=%CONFIGURATION% .. %CMAKE_CONFIGURE_FLAGS% 
    - cmake --build . --config %CONFIGURATION% %CMAKE_BUILD_FLAGS%

test_script:
    - ctest -C %CONFIGURATION% --output-on-failure
